name: jinya_cms_api
description: Implementation of the Jinya CMS API written in Dart for use with Flutter and other Dart apps
version: 1.0.12
homepage: https://github.com/Jinya-CMS/jinya-cms-dart-sdk

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.1
  json_serializable: 6.5.4
  build_runner: 2.3.2
