name: jinya_cms_api
description: Implementation of the Jinya CMS API written in Dart for use with Flutter and other Dart apps
version: 2.0.0
homepage: https://gitlab.imanuel.dev/jinya-cms/jinya-cms-dart-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
