name: jinya_cms
description: Implementation of the Jinya CMS API written in Dart for use with Flutter and other Dart apps
version: 1.0.0
homepage: https://github.com/Jinya-CMS/jinya-dart-sdk

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: 2.2.0
